version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:8080
      - --advertise-kafka-addr internal://redpanda:8080
      - --pandaproxy-addr internal://0.0.0.0:8082
      - --advertise-pandaproxy-addr internal://redpanda:8082
    ports:
      - "8080:8080"
      - "8082:8082"
      - "9644:9644"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rides-backend
    ports:
      - "3000:3000"
    env_file:
    - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - redpanda
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rides-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped